/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.dbConnector;
import config.session;
import dhp.DHPMAIN;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus VivoBook
 */
public class addDiagnosis extends javax.swing.JFrame {

    /**
     * Creates new form addDiagnosis
     */
    public addDiagnosis() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        p_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        diagnose = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        p_lname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        acc_fname = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        doc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-30.png"))); // NOI18N
        jLabel10.setText("SEARCH");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(600, 110, 90, 40);

        p_name.setEditable(false);
        p_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p_name.setToolTipText("");
        p_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_nameMouseClicked(evt);
            }
        });
        p_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_nameActionPerformed(evt);
            }
        });
        jPanel1.add(p_name);
        p_name.setBounds(300, 150, 200, 40);

        jScrollPane1.setFocusable(false);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        diagnose.setColumns(20);
        diagnose.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        diagnose.setRows(5);
        jScrollPane1.setViewportView(diagnose);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 310, 390, 140);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 460, 130, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText(" CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 460, 130, 40);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD DIAGNOSIS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 740, 60));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 780, 90);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Input Diagnosis Here:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 290, 290, 16);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Patient's Name:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 150, 220, 40);

        p_lname.setEditable(false);
        p_lname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        p_lname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_lnameMouseClicked(evt);
            }
        });
        p_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_lnameActionPerformed(evt);
            }
        });
        jPanel1.add(p_lname);
        p_lname.setBounds(500, 150, 190, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/doc_nobg.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 190, 300, 250);

        acc_fname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        acc_fname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_fname.setText("doctor's name");
        jPanel1.add(acc_fname);
        acc_fname.setBounds(10, 440, 290, 22);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setText("please enter the first name and last name the doctor");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(400, 220, 290, 16);

        doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docActionPerformed(evt);
            }
        });
        jPanel1.add(doc);
        doc.setBounds(400, 240, 290, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setText("please enter the first name and last name of patient");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(300, 130, 290, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Doctor's name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 240, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void p_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_nameActionPerformed
    pickPatient pp = new pickPatient();
                pp.setVisible(true);
                this.dispose();               // TODO add your handling code here:
    }//GEN-LAST:event_p_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                        
    // 1. Initialize the tools we need
    config.dbConnector db = new config.dbConnector(); // This fixes the 'db' error
    config.session sess = config.session.getInstance(); // This fixes the 'sess' error
    
    String pn = p_name.getText();
    String ln = p_lname.getText();
    String doctor = doc.getText();
    String d = diagnose.getText();
    
    // We need a variable for the User ID (assuming you get it from session or query)
    int userId = sess.getUid(); 

    try (java.sql.Connection con = db.getConnection()) {
        
        String insertQuery = "INSERT INTO tbl_diagnosis (doctor, diagnosis, patient, u_id) VALUES (?, ?, ?, ?)";
        
        // 2. Create the insertStmt (This fixes the 'insertStmt' error)
        try (java.sql.PreparedStatement insertStmt = con.prepareStatement(insertQuery)) {
            insertStmt.setString(1, doctor);          
            insertStmt.setString(2, d);
            insertStmt.setString(3, pn);
            insertStmt.setInt(4, userId);

            int rowsInserted = insertStmt.executeUpdate();
            
            if (rowsInserted > 0) {
                // 3. Record the log using the info from session
                String user = sess.getUsername();
                String type = sess.getType(); 
                
                db.recordLog(user, type, "Added diagnosis for: " + pn + " " + ln);

                javax.swing.JOptionPane.showMessageDialog(null, "Added successfully!");
                
                // Open the next view
                ViewDiagnosisDoctor vd = new ViewDiagnosisDoctor();
                vd.setVisible(true);
                this.dispose(); 
            }
        }
        
    } catch (java.sql.SQLException ex) {
        System.out.println("SQL Error: " + ex.getMessage());
    }
 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 ViewDiagnosisDoctor vd = new ViewDiagnosisDoctor();
                vd.setVisible(true);
                this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
session sess = session.getInstance();
       if(sess.getUid() == 0)
       {
           
           DHPMAIN l = new DHPMAIN();
           l.setVisible(true);
           this.dispose();
           JOptionPane.showMessageDialog(null,"No Account, Login FIrst");
       }else
       {
           acc_fname.setText("Doc. " + sess.getFname());
             
           

       }               // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void p_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_nameMouseClicked
     pickPatient pp = new pickPatient();
            pp.setVisible(true);
            this.dispose();          
    }//GEN-LAST:event_p_nameMouseClicked

    private void p_lnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_lnameMouseClicked
     pickPatient pp = new pickPatient();
            pp.setVisible(true);
            this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_p_lnameMouseClicked

    private void p_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_lnameActionPerformed
     pickPatient pp = new pickPatient();
            pp.setVisible(true);
            this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_p_lnameActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
    pickPatient pp = new pickPatient();
            pp.setVisible(true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addDiagnosis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDiagnosis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_fname;
    private javax.swing.JTextArea diagnose;
    private javax.swing.JTextField doc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField p_lname;
    public javax.swing.JTextField p_name;
    // End of variables declaration//GEN-END:variables

    void setUid(String userId) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setFname(String fname) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setLname(String lname) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
